name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y libopenblas0 libopenblas64-0
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt
      - name: Build
        run: cargo build --verbose
      - name: Check formatting
        run: cargo fmt --check --verbose
      - name: Clippy
        run: cargo clippy
      - name: Run tests
        run: cargo test --verbose
